/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.poly.forms;

import edu.poly.panels.ManageStudentPanel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dzboy2k
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnBoard = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        tlbManageStudent = new javax.swing.JButton();
        tlbManageMark = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        tlbExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSetting = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuManageStudent = new javax.swing.JMenuItem();
        mnuManageMark = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuHelpContent = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Sinh Viên");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fpoly.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpnBoard.addTab("Thông tin", jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");

        jToolBar1.setRollover(true);

        tlbManageStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Adduser.png"))); // NOI18N
        tlbManageStudent.setFocusable(false);
        tlbManageStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlbManageStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlbManageStudentActionPerformed(evt);
            }
        });
        jToolBar1.add(tlbManageStudent);

        tlbManageMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gpa.jpg"))); // NOI18N
        tlbManageMark.setFocusable(false);
        tlbManageMark.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlbManageMark.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tlbManageMark);
        jToolBar1.add(jSeparator3);

        tlbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/poweroff.png"))); // NOI18N
        tlbExit.setFocusable(false);
        tlbExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlbExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlbExitActionPerformed(evt);
            }
        });
        jToolBar1.add(tlbExit);

        jMenu1.setText("Hệ Thống");

        mnuSetting.setText("Cấu Hình");
        jMenu1.add(mnuSetting);
        jMenu1.add(jSeparator1);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        mnuExit.setText("Thoát");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        mnuManageStudent.setText("Quản Lý Sinh Viên");
        mnuManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageStudentActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManageStudent);

        mnuManageMark.setText("Quản Lý Điểm");
        mnuManageMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageMarkActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManageMark);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Trợ Giúp");

        mnuHelpContent.setText("Tài Liệu Hướng Dẫn");
        jMenu4.add(mnuHelpContent);
        jMenu4.add(jSeparator2);

        mnuAbout.setText("Giới Thiệu");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        jMenu4.add(mnuAbout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpnBoard)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tpnBoard)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageStudentActionPerformed
        ManageStudentPanel pnl = new ManageStudentPanel();
        tpnBoard.addTab("Quản Lý Sinh Viên", pnl);
        tpnBoard.setSelectedComponent(pnl);
    }//GEN-LAST:event_mnuManageStudentActionPerformed

    private void mnuManageMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManageMarkActionPerformed

    private void tlbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlbExitActionPerformed
        mnuExitActionPerformed(evt);
    }//GEN-LAST:event_tlbExitActionPerformed

    private void tlbManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlbManageStudentActionPerformed
        mnuManageStudentActionPerformed(evt);
    }//GEN-LAST:event_tlbManageStudentActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        StringBuilder sb = new StringBuilder();
        sb.append("Poly Student Management System\n");
        sb.append("Author: Nguyen Ngoc Anh");
        
        JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_mnuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuHelpContent;
    private javax.swing.JMenuItem mnuManageMark;
    private javax.swing.JMenuItem mnuManageStudent;
    private javax.swing.JMenuItem mnuSetting;
    private javax.swing.JButton tlbExit;
    private javax.swing.JButton tlbManageMark;
    private javax.swing.JButton tlbManageStudent;
    private javax.swing.JTabbedPane tpnBoard;
    // End of variables declaration//GEN-END:variables
}
